include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 错误预防
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true

    # 代码风格
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_type_to_string: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true

    # Flutter 特定
    use_build_context_synchronously: true
    sized_box_for_whitespace: true
